{{- if gt (int .Values.server.workers) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto-kube.worker" . }}
  labels:
    app: {{ template "presto-kube.name" . }}
    chart: {{ template "presto-kube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: "worker"
data:
  PRESTO_CONF_COORDINATOR: "false"
  PRESTO_CONF_HTTP_PORT: "{{ .Values.server.config.port }}"
  PRESTO_CONF_QUERY_MAX_MEMORY: "{{ .Values.server.config.query.maxMemory }}"
  PRESTO_CONF_QUERY_MAX_MEMORY_PER_NODE: "{{ .Values.server.config.query.maxMemoryPerNode }}"
  PRESTO_CONF_DISCOVERY_SERVER_ENABLED: "true"
  PRESTO_CONF_DISCOVERY_URI: "http://{{ template "presto-kube.fullname" . }}:{{ .Values.server.config.port }}"
  PRESTO_JVM_MEMORY_MS_MX: "{{ .Values.server.jvm.memory }}"
  PRESTO_JVM_H1_HEAP_REGION_SIZE: "{{ .Values.server.jvm.g1.heapRegionSize }}"
  PRESTO_LOG_LEVEL: "{{ .Values.server.log.level }}"
  PRESTO_NODE_ENV: "{{ .Values.server.node.environment }}"
  
---
{{- end }}