apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "presto-kube.coordinator" . }}
  labels:
    app: {{ template "presto-kube.name" . }}
    chart: {{ template "presto-kube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: coordinator
spec:
  selector:
    matchLabels:
      app: {{ template "presto-kube.name" . }}
      release: {{ .Release.Name }}
      component: coordinator
  template:
    metadata:
      labels:
        app: {{ template "presto-kube.name" . }}
        release: {{ .Release.Name }}
        component: coordinator
    spec:
      containers:
        - name: {{ .Chart.Name }}-coordinator
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-coord
              containerPort: {{ .Values.server.config.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/cluster
              port: http-coord
          readinessProbe:
            httpGet:
              path: /v1/cluster
              port: http-coord
          envFrom:
            - configMapRef:
                name: {{ template "presto-kube.coordinator" . }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}