apiVersion: v1
kind: Service
metadata:
  name: {{ template "presto-kube.fullname" . }}
  labels:
    app: {{ template "presto-kube.name" . }}
    chart: {{ template "presto-kube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.server.config.port }}
      targetPort: http-coord
      protocol: TCP
      name: http-coord
  selector:
    app: {{ template "presto-kube.name" . }}
    release: {{ .Release.Name }}
    component: coordinator